#!/usr/bin/env bash

set -euo pipefail

# Install packages
./packages/apt
./packages/custom
./packages/flatpak
./packages/other

# find the installers aqh | while read installer ; do sh -c "${installer}" ; done

./post-install